apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo-ing
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /echo
            pathType: Prefix
            backend:
              service:
                name: echo-svc
                port:
                  number: 80
